### ISSUE TITLE
[Feature Request] Display original Japanese EQ name

### ISSUE THREAD

**Issue by rogeraabbccdd** [RodrigoLeiteF/WeebBot-v2#15]
Is it possible to add a setting that make bot display original Japanese EQ name?

**Comment by SkyLeite** [comment]
Should be. Gonna work on that after the planned rewrite.

**Comment by SkyLeite** [comment]
I added this but I don't remember on what commit it was. LOL

**Comment by rogeraabbccdd** [comment]
WTF ROFL.
Anyway, Thanks for this amazing feature.

**Comment by SkyLeite** [comment]
No problem o/
