### ISSUE TITLE
Double alerts on public bot

### ISSUE THREAD

**Issue by SkyLeite** [RodrigoLeiteF/WeebBot-v2#22]
Somehow doesn't happen on self-hosted, only on Weeb Bot.

**Comment by reveriadive** [comment]
Does this help at all? There is a delay between these double posts.
![rewards](https://user-images.githubusercontent.com/17341158/29904745-e85af2b0-8dcf-11e7-8e73-9dc777d08aaf.png)

**Comment by SkyLeite** [comment]
I think I know why this is happening. Basically the checks for a new EQ runs on an infinite loop every 5 seconds by comparing the newest info on the API to the cache. When it detects a new EQ, it sends an alert to the appropriate servers **and only then it updates the cache**. Since the bot is in almost 900 servers now, I'm assuming it's taking it too long to send all the messages, so by the time the next check happens, the cache hasn't been updated yet and another alert is fired.

As a temporary fix, I increased the check rate to once every 25 seconds. Gonna leave this open for a bit to make sure that's what's happening.
